/* soapLacuisineBindingProxy.h
   Generated by gSOAP 2.8.104 for lacuisine.h

gSOAP XML Web services tools
Copyright (C) 2000-2020, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapLacuisineBindingProxy_H
#define soapLacuisineBindingProxy_H
#include "soapH.h"

    class SOAP_CMAC LacuisineBindingProxy {
      public:
        /// Context to manage proxy IO and data
        struct soap *soap;
        /// flag indicating that this context is owned by this proxy and should be deleted by the destructor
        bool soap_own;
        /// Endpoint URL of service 'LacuisineBindingProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in lacuisine.h, if any
        /// Construct a proxy with new managing context
        LacuisineBindingProxy();
        /// Copy constructor
        LacuisineBindingProxy(const LacuisineBindingProxy& rhs);
        /// Construct proxy given a shared managing context
        LacuisineBindingProxy(struct soap*);
        /// Construct proxy given a shared managing context and endpoint URL
        LacuisineBindingProxy(struct soap*, const char *soap_endpoint_url);
        /// Constructor taking an endpoint URL
        LacuisineBindingProxy(const char *soap_endpoint_url);
        /// Constructor taking input and output mode flags for the new managing context
        LacuisineBindingProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        LacuisineBindingProxy(const char *soap_endpoint_url, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        LacuisineBindingProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and its managing context, when the context was allocated by the constructor
        virtual ~LacuisineBindingProxy();
        /// Initializer used by constructors
        virtual void LacuisineBindingProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual LacuisineBindingProxy *copy();
        /// Copy assignment
        LacuisineBindingProxy& operator=(const LacuisineBindingProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault subcode QName string (NULL when absent)
        virtual const char *soap_fault_subcode();
        /// Get SOAP Fault string/reason (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail XML string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        //
        /// Web service synchronous operation 'OpenUserSession' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int OpenUserSession(ns1__OpenUserSessionRequestType *ns1__OpenUserSessionRequest, ns1__OpenUserSessionResponseType &ns1__OpenUserSessionResponse) { return this->OpenUserSession(NULL, NULL, ns1__OpenUserSessionRequest, ns1__OpenUserSessionResponse); }
        /// Web service synchronous operation 'OpenUserSession' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int OpenUserSession(const char *soap_endpoint_url, const char *soap_action, ns1__OpenUserSessionRequestType *ns1__OpenUserSessionRequest, ns1__OpenUserSessionResponseType &ns1__OpenUserSessionResponse) { return this->send_OpenUserSession(soap_endpoint_url, soap_action, ns1__OpenUserSessionRequest) || this->recv_OpenUserSession(ns1__OpenUserSessionResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_OpenUserSession' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_OpenUserSession(const char *soap_endpoint_url, const char *soap_action, ns1__OpenUserSessionRequestType *ns1__OpenUserSessionRequest);
        /// Web service asynchronous operation 'recv_OpenUserSession' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_OpenUserSession(ns1__OpenUserSessionResponseType &ns1__OpenUserSessionResponse);
        //
        /// Web service synchronous operation 'CloseUserSession' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int CloseUserSession(ns1__CloseUserSessionRequestType *ns1__CloseUserSessionRequest, ns1__CloseUserSessionResponseType &ns1__CloseUserSessionResponse) { return this->CloseUserSession(NULL, NULL, ns1__CloseUserSessionRequest, ns1__CloseUserSessionResponse); }
        /// Web service synchronous operation 'CloseUserSession' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int CloseUserSession(const char *soap_endpoint_url, const char *soap_action, ns1__CloseUserSessionRequestType *ns1__CloseUserSessionRequest, ns1__CloseUserSessionResponseType &ns1__CloseUserSessionResponse) { return this->send_CloseUserSession(soap_endpoint_url, soap_action, ns1__CloseUserSessionRequest) || this->recv_CloseUserSession(ns1__CloseUserSessionResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_CloseUserSession' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_CloseUserSession(const char *soap_endpoint_url, const char *soap_action, ns1__CloseUserSessionRequestType *ns1__CloseUserSessionRequest);
        /// Web service asynchronous operation 'recv_CloseUserSession' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_CloseUserSession(ns1__CloseUserSessionResponseType &ns1__CloseUserSessionResponse);
    };
#endif
